#!/usr/bin/python3


def print_matrix_integer(matrix=[[]]):

    if len(matrix) > 0:
        i = j = 0
        while i < len(matrix):
            while j < len(matrix[i]):
                print("{:d}".format(matrix[i][j]), end=" ")
                j += 1
            print("{:d}".format(matric[i][j]))
            j = 0
            i += 1
