#!/usr/bin/python3


def add_tuple(tuple_a=(), tuple_b=()):

    list_add = []
    if len(tuple_a) == 2 and len(tuple_b) == 2:
        list_add = tuple_a + tuple_b 
    for i in range(0, len(tuple_a) 
        print(tuple_a[i])

#    print(list_add)    
    return (35000)
